/* Enum2H auto-generated custom resource - DO NOT EDIT BY HAND!! */
/* Created from file: mod_id.h */


typedef struct tagENUMSTRUCT
{
	int		nID;				/* integer value of enum item */
	char	*pszName;			/* pointer to null-terminated item name string */
	char	*pszDescription;	/* pointer to null-terminated description string*/
} ENUMSTRUCT;

static ENUMSTRUCT Modules[] = 
{
	{0, "MODID_DEFAULT", "Other unknown modules"},
	{1, "MODID_RN", "Other render routines"},
	{2, "MODID_DL", "Other display list routines"},
	{3, "MODID_NM", "Name table"},
	{4, "MODID_RECORDER", "Recorder"},
	{5, "MODID_PLAYBACK", "Playback"},
	{6, "MODID_ADJACENC", "Generate convex adjacency info"},
	{7, "MODID_ARRAY", "Array routines"},
	{8, "MODID_CALLBACK", "Callback routines"},
	{9, "MODID_DEBUG", "Debug module"},
	{10, "MODID_DISP", "SGLDirect ISP functions"},
	{11, "MODID_DLCAMERA", "SGL Camera display list"},
	{12, "MODID_DLCONVEX", "SGL Convex display list"},
	{13, "MODID_DLDELETE", "SGL Display list editing"},
	{14, "MODID_DLGLOBAL", "SGL Display list globals"},
	{15, "MODID_DLINES", "SGLDirect Line functions"},
	{16, "MODID_DLLIGHTS", "SGL Lights display list"},
	{17, "MODID_DLLISTS", "SGL Display list editing"},
	{18, "MODID_DLLOD", "SGL Display list level of detail"},
	{19, "MODID_DLMATER", ""},
	{20, "MODID_DLMESH", ""},
	{21, "MODID_DLNEWTRN", ""},
	{22, "MODID_DLOBJECT", ""},
	{23, "MODID_DLPOINT", ""},
	{24, "MODID_DLQUALIT", ""},
	{25, "MODID_DLTRANSF", ""},
	{26, "MODID_DPOINT", ""},
	{27, "MODID_DREGION", ""},
	{28, "MODID_DSHADE", ""},
	{29, "MODID_DSPRITE", ""},
	{30, "MODID_DTEX", ""},
	{31, "MODID_DTEXNP", ""},
	{32, "MODID_DTRI", ""},
	{33, "MODID_DTSP", ""},
	{34, "MODID_DVDEVICE", ""},
	{35, "MODID_ERROR", ""},
	{36, "MODID_LDBIN", ""},
	{37, "MODID_LDBMP", ""},
	{38, "MODID_LIST", ""},
	{39, "MODID_METRICS", ""},
	{40, "MODID_NM_IMP", ""},
	{41, "MODID_PARMBUFF", ""},
	{42, "MODID_PKISP", ""},
	{43, "MODID_PKTSP", ""},
	{44, "MODID_PROFILE", ""},
	{45, "MODID_PVRD", ""},
	{46, "MODID_RNCAMERA", ""},
	{47, "MODID_RNCONVEX", ""},
	{48, "MODID_RNCONVPR", ""},
	{49, "MODID_RNFSHADE", ""},
	{50, "MODID_RNGLOBAL", ""},
	{51, "MODID_RNLIGHTS", ""},
	{52, "MODID_RNLOD", ""},
	{53, "MODID_RNMATER", ""},
	{54, "MODID_RNMESH", ""},
	{55, "MODID_RNPOINT", ""},
	{56, "MODID_RNQUALIT", ""},
	{57, "MODID_RNREJECT", ""},
	{58, "MODID_RNRENDER", ""},
	{59, "MODID_RNSHADE", ""},
	{60, "MODID_RNSHADOW", ""},
	{61, "MODID_RNSHADRJ", ""},
	{62, "MODID_RNSTATE", ""},
	{63, "MODID_RNTEX", ""},
	{64, "MODID_RNTRANSF", ""},
	{65, "MODID_RNTRAV", ""},
	{66, "MODID_SGL_INIT", ""},
	{67, "MODID_SGL_MATH", ""},
	{68, "MODID_SGLLITE", ""},
	{69, "MODID_SGLMEM", ""},
	{70, "MODID_SGLTRI", ""},
	{71, "MODID_SINGMATH", ""},
	{72, "MODID_TEXAPI", ""},
	{73, "MODID_TMALLOC", ""},
	{74, "MODID_TXMOPS", ""},
	{75, "MODID_BRDCFG", ""},
	{76, "MODID_BRDSETUP", ""},
	{77, "MODID_DISPLAY", ""},
	{78, "MODID_HEAP", ""},
	{79, "MODID_HWDEVICE", ""},
	{80, "MODID_PVRDDLL", ""},
	{81, "MODID_PVROSIF", ""},
	{82, "MODID_SGLWIN", ""},
	{83, "MODID_SYSTEM", ""},
	{84, "MODID_TEXIF", ""},
	{85, "MODID_VERRC", ""},
	{86, "MODID_W32DLL", ""},
	{87, "MODID_HWREGS", ""},
	{88, "MODID_TEXAS", ""},
	{89, "MODID_NEW_THIN", ""},
	{90, "MODID_D3DISP", ""},
	{91, "MODID_D3DTRI", ""}
};

#define NUM_ITEMS_IN_MODULES_ARRAY 92

/* end of file */
